project:
  type: website
  output-dir: docs

website:
  title: "Shawn S. Voutour"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: research.qmd
        text: Research
    right:
      - icon: twitter
        href: https://twitter.com/ShawnVoutour
      - icon: github
        href: https://github.com/shawnmazdey
  search: false
  page-footer:
    left: "Copyright Â© 2023 - Shawn S. Voutour"
      

format:
  html:
    theme: darkly
    css: styles.css
    toc: false
    page-layout: full



